name: hygiene_vendor_app
description: Hygiene vendor certification app
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add your packages HERE ðŸ‘‡
  flutter_launcher_icons: ^0.13.1
  provider: ^6.0.5
  image_picker: ^1.2.1
  geolocator: ^14.0.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
assets:
    - assets/screen.png
    - assets/vendor_qr.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
